# Generated by Django 5.1 on 2024-09-02 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=100)),
                ("plate", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("createdby", models.IntegerField()),
                ("like", models.IntegerField()),
                (
                    "photo",
                    models.ImageField(
                        upload_to="img",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [".png", ".jpg", ".jpeg"]
                            )
                        ],
                    ),
                ),
            ],
        ),
    ]
