# Generated by Django 5.1 on 2024-08-27 23:05

from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=20)),
                ("plate", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                
                ("like",models.IntegerField(default=0)),
                ("photo", models.FileField(upload_to='img')),
                
                
            ],
        ),
    ]
