# Generated by Django 4.1 on 2024-08-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_car_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="created",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="car",
            name="like",
            field=models.IntegerField(max_length=0),
        ),
    ]
