# Generated by Django 4.1 on 2024-08-31 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_car_created_alter_car_like"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="created",
            new_name="createdby",
        ),
        migrations.AlterField(
            model_name="car",
            name="photo",
            field=models.FileField(
                upload_to="img/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg"]
                    )
                ],
            ),
        ),
    ]
