# Generated by Django 4.1 on 2024-08-31 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_car_likes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="likes",
            new_name="like",
        ),
    ]
