# Generated by Django 4.1 on 2024-08-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_car_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="createdby",
            field=models.IntegerField(),
        ),
    ]
