# Generated by Django 4.1 on 2024-09-01 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_car_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="photo",
            field=models.ImageField(
                upload_to="img",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [".png", ".jpg", ".jpeg"]
                    )
                ],
            ),
        ),
    ]
